<a href="https://colab.research.google.com/github/kamala999/Python-test-code/blob/main/Day15_9_Stacking_and_splitting10_Shape_Manipulations_Python_Gen_AI1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
A = np.array([45,60,90])
B = np.array([16,18,20])
print(np.diff(A)) #60-45, 90 -60

[15 30]


In [3]:
Balance = np.array([120,150,300])
profits = np.diff(Balance)
print(profits)

[ 30 150]


In [4]:
#statastics
A = np.array([23,54,34,45,49,41,61,77])
print(np.mean(A))# Avarage

48.0


In [6]:
A = np.array([23,54,34,45,49,41,61,77])
print(np.median(A)) #23,34,41,45,49,54,61,77 # 45+49/2

47.0


In [7]:
A = np.array([23,54,34,45,49,41,61,77])
print(np.var(A))# variance

240.75


In [8]:
A = np.array([23,54,34,45,49,41,61,77])
print(np.std(A))# standerd deviation

15.5161206491829


In [9]:
#trigunametory
print(np.pi) # output ---radians

3.141592653589793


In [10]:
print(np.rad2deg(np.pi))

180.0


In [15]:
val = np.array([np.pi/6, np.pi/4, np.pi/3, np.pi/2, np.pi])
print("this output will be in Randiance")
print(val)# this output will be in Randiance
print("convert this in degree s")
print(np.rad2deg(val))

this output will be in Randiance
[0.52359878 0.78539816 1.04719755 1.57079633 3.14159265]
convert this in degree s
[ 30.  45.  60.  90. 180.]


In [16]:
rval = np.array([30,45,90,120,180])
print("This all numbers are in degree s now conver into radiance")
print(np.deg2rad(rval))

This all numbers are in degree s now conver into radiance
[0.52359878 0.78539816 1.57079633 2.0943951  3.14159265]


In [17]:
print(np.sin(2))
print(np.cos(2))
print(np.tan(2))

0.9092974268256817
-0.4161468365471424
-2.185039863261519


In [19]:
a = 8
b = 6
h = np.hypot(a,b)#hypoteunes
print(h)

10.0


In [18]:
#inverce
print(np.arcsin(90))
print(np.arccos(90))
print(np.arctan(90))

nan
nan
1.5596856728972892


<ipython-input-18-f5e6681c9203>:2: RuntimeWarning: invalid value encountered in arcsin
  print(np.arcsin(90))
<ipython-input-18-f5e6681c9203>:3: RuntimeWarning: invalid value encountered in arccos
  print(np.arccos(90))


In [25]:
A = np.array([45,60,90])
B = np.array([16,18,20])
print(np.union1d(A,B))

[16 18 20 45 60 90]


In [26]:
A = np.array([12,45,60,90])
B = np.array([16,18,12,20])
print(np.intersect1d(A,B))# common values from a and b

[12]


In [27]:
A = np.array([12,45,60,90])
B = np.array([16,18,12,20])
print(np.setdiff1d(A,B))

[45 60 90]


In [28]:
#joins it will multiply two arrays and add the totall
A = np.array([1,3,4])
B = np.array([4,2,5])
print(np.inner(A,B))# 1*4+3*2+4*5=30


30


In [29]:
A = np.array([1,3,4])  #1*4,1*2,1*5
B = np.array([4,2,5])  #3*4,3*2,3*5
print(np.outer(A,B))  #4*4,4*2,*4*5  the first row each number multiply with secon row all  numbers and print the list

[[ 4  2  5]
 [12  6 15]
 [16  8 20]]


In [30]:
A = np.array([1,3,4])
B = np.array([4,2,5])
print(np.cross(A,B))
# here you have to observe when you caluculate cross matrice one colom will be silent, next time second colom silent, next 3rd colom wiil be silent leke below
#3*4-4*2=7, -1*5-4*4=11, 1*2-4*3= -10

[  7  11 -10]


In [2]:
#from parent import child
from numpy import random as rd

In [3]:
arr = rd.rand() # limit 0 to 1
print(arr)

0.295236427544487


In [4]:
arr = rd.rand(4) # rand(size) random === less then 1
print(arr)

[0.35288499 0.06741183 0.35707074 0.42330923]


In [9]:
arr = rd.randint(4) # randint(limit) #0,1,2,3
print(arr)

2


In [13]:
#randint(limit, size = (number)) #1d array
arr = rd.randint(50, size = (3)) # Genarate 3 random numbers less then 50
print(arr)

[25 12  1]


In [16]:
#randint(limit, size = (number)) #2d array
arr = rd.randint(50, size = (3,4)) # Genarate 3 random numbers less then 50
print(arr)
print(arr.ndim)

[[22 31 25 49]
 [40 16 19 14]
 [35 19 26 44]]
2


In [17]:
arr = np.array([9,4,3,1,2])
arr2 = rd.shuffle(arr)
print(arr2)

None


In [18]:
arr = np.array([9, 4, 3, 1, 2])
np.random.shuffle(arr)
print(arr)

[1 3 2 9 4]


In [20]:
L = np.log(10)
print(L)

2.302585092994046


In [22]:
L = 10
print(np.log(L))# natural log

2.302585092994046


In [23]:
L = 10
print(np.log2(L))#log base 2

3.321928094887362


In [24]:
L = 10
print(np.log10(L))#log base 10

1.0


In [30]:
#shape manipulation
A = rd.randint(50, size = (2,2))
print(A)

[[29 16]
 [18  5]]


In [32]:
Z = np.arange(2,8).reshape(2,3)
print(Z)

[[2 3 4]
 [5 6 7]]


In [33]:
s = np.array([2,4,6,7,8,12,14,15,]).reshape(4,2)
print(s)

[[ 2  4]
 [ 6  7]
 [ 8 12]
 [14 15]]


In [34]:
a = np.array([2,4,6,7,8,12,14,15,])
b = a.reshape(4,2)
print(b)

[[ 2  4]
 [ 6  7]
 [ 8 12]
 [14 15]]


In [36]:
a = np.array([2,4,6,7,8,12,14,15,])
a.reshape(4,2)#changes are not shaved
print(a)

[ 2  4  6  7  8 12 14 15]


In [37]:
a = np.array([2,4,6,7,8,12,14,15,])
a.resize(4,2)#changes are  shaved to original array
print(a)

[[ 2  4]
 [ 6  7]
 [ 8 12]
 [14 15]]
