<a href="https://colab.research.google.com/github/kamala999/Python-test-code/blob/main/Day_14_Numpy_5_1%2C2_%26_3D_arrays_and_indexing_6_Operations_in_NUMPY_7_Operation_in_NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [ ]:
#linespace
A = np.linspace(0.11,2.2,8) #start, end, numbers
print(A)
# 0.11 and 2.2 in between 8 numbers spliting arange  will print with common difrence


[0.11       0.40857143 0.70714286 1.00571429 1.30428571 1.60285714
 1.90142857 2.2       ]


In [ ]:
maths:

In [ ]:
A = np.array([3,1,5,6])
B = np.array([5,8,9,1])

print(A-B)
print(A+B)


[-2 -7 -4  5]
[ 8  9 14  7]


In [ ]:
A = np.array([[2,3],[5,7]])
B = np.array([[1,9],[4,2]])

print(A)
print(B)

[[2 3]
 [5 7]]
[[1 9]
 [4 2]]


In [ ]:
print(A@B)#matrics maltiplication
# this is multiplicatin matrics like 2*1+3*4=14,2*9+3*2=24,5*1+7*4=33,5*9+7*2=59

[[14 24]
 [33 59]]


In [ ]:
print(A*B)#vector multiplication

[[ 2 27]
 [20 14]]


In [ ]:
print(A.sum())

17


In [ ]:
A = np.array([[2,3],[5,7]])
B = np.array([[1,9],[4,2]])
print(A)
print(B)
print("this is sum of A")
print(A.sum())
print("this is sum of A colom wiae")
#Axis=0 for coloms, and Axis=1 for rows
print(A.sum(axis=0)) #colom wise added
print("this is sum of A row wise")
print(A.sum(axis=1)) #row wise added

[[2 3]
 [5 7]]
[[1 9]
 [4 2]]
this is sum of A
17
this is sum of A colom wiae
[ 7 10]
this is sum of A row wise
[ 5 12]


In [ ]:
A = np.array([[2,3],[5,7]])
B = np.array([[1,9],[4,2]])
print(A)
print(B)
print("this print the max of number in A ")
print(A.max())
print("this print the max of number colom wise in A ")
print(A.max(axis=0))
print("this print the max of number row wise in A ")
print(A.max(axis=1))


[[2 3]
 [5 7]]
[[1 9]
 [4 2]]
this print the max of number in A 
7
this print the max of number colom wise in A 
[5 7]
this print the max of number row wise in A 
[3 7]


In [ ]:
A = np.array([[2,3],[5,7]])
B = np.array([[1,9],[4,2]])
print(A)
print(B)
print("this print the max of number in A ")
print(A.min())
print("this print the max of number colom wise in A ")
print(A.min(axis=0))
print("this print the max of number row wise in A ")
print(A.min(axis=1))

[[2 3]
 [5 7]]
[[1 9]
 [4 2]]
this print the max of number in A 
2
this print the max of number colom wise in A 
[2 3]
this print the max of number row wise in A 
[2 5]


In [ ]:
A = np.array([[2,3],[5,7]])
B = np.array([[1,9],[4,2]])
print(A)
print("cumilative sum:")
print(A.cumsum()) #2,3,5,7 ==> 2, 2+3=5, 2+3+5=10, 2+3+5+7=17

[[2 3]
 [5 7]]
cumilative sum:
[ 2  5 10 17]


In [ ]:
A = np.array([[2,3],[5,7]])
B = np.array([[1,9],[4,2]])
print(A)
print("cumilative prod:")
print(A.cumprod()) #2,3,5,7 ==> 2, 2*3=6, 2*3*5=30, 2*3*5*7=210

[[2 3]
 [5 7]]
cumilative prod:
[  2   6  30 210]


In [ ]:
ar1 = np.array([14,23,58,78])
ar2 = np.array([45,88,91,24])
np.add(ar1,ar2)

array([ 59, 111, 149, 102])

In [ ]:
ar1 = np.array([14,23,58,78])
ar2 = np.array([45,88,91,24])
np.subtract(ar1,ar2)

array([-31, -65, -33,  54])

In [ ]:
ar1 = np.array([14,23,58,78])
ar2 = np.array([45,88,91,24])
np.multiply(ar1,ar2)

array([ 630, 2024, 5278, 1872])

In [3]:
ar1 = np.array([14,23,58,78])
ar2 = np.array([45,88,91,24])
np.divide(ar1,ar2)

array([0.31111111, 0.26136364, 0.63736264, 3.25      ])

In [5]:
ar1 = np.array([14,23,58,78])
ar2 = np.array([4,2,4,2])
np.mod(ar1,ar2)

array([2, 1, 2, 0])

In [7]:
ar1 = np.array([14,23,58,78])
ar2 = np.array([4,2,4,2])
np.divmod(ar1,ar2)

(array([ 3, 11, 14, 39]), array([2, 1, 2, 0]))

In [3]:
#sorting and serching
A = np.array(['mango','banana','appil','grape','strawbarry','orange'])
print(np.sort(A))

['appil' 'banana' 'grape' 'mango' 'orange' 'strawbarry']


In [6]:
sr = np.array([22,44,33,45,68,77,87,100])
ind = np.where(sr%4 == 0)
print(ind)

(array([1, 4, 7]),)


In [8]:
sr = np.array([22,44,33,45,68,77,87,100])
ind = np.where(sr%4 == 0)
print(ind)

sr[ind]

(array([1, 4, 7]),)


array([ 44,  68, 100])

In [9]:
names = np.array(["kamal","vijay","srinu","rami","lakshmi","vasantha"])
ind = np.where(names == 'lakshmi')
print(ind)

(array([4]),)


In [12]:
arn = np.array([35,34,21,25,45,52,66])
ind = np.where(arn > 25)
print(ind)
arn[ind]

(array([0, 1, 4, 5, 6]),)


array([35, 34, 45, 52, 66])

In [14]:
#Rounding functions
#trunc will print with out .

ro = np.array([3.6, 9.1])
rn = np.array([-3.6, -9.1])
print(np.trunc(ro))
print(np.trunc(rn))

[3. 9.]
[-3. -9.]


In [15]:
#Rounding functions
#trunc will print with out .
#around will print the correct nummbers with near by like 5.1 = 5, 5.7 =6,

ro = np.array([3.6, 9.1])
rn = np.array([-3.6, -9.1])
print(np.around(ro))
print(np.around(rn))

[4. 9.]
[-4. -9.]


In [16]:
#ceil will convert the Maximum values near by that value
ro = np.array([3.6, 9.1])
rn = np.array([-3.6, -9.1])
print(np.ceil(ro))
print(np.ceil(rn))

[ 4. 10.]
[-3. -9.]


In [17]:
#floor will convert the minimum values near by that value
ro = np.array([3.6, 9.1])
rn = np.array([-3.6, -9.1])
print(np.floor(ro))
print(np.floor(rn))

[3. 9.]
[ -4. -10.]


In [26]:
#using user-defining function to add array
#formula
# def funname:
   #statement
#np.frompyfunc(funname,inputs,outputs)
def ad(a,b):
   print(a+b)

m = np.frompyfunc(ad,2,1)
print(m([2,3],[4,5]))


6
8
[None None]


In [25]:
def name(a,b):
   print(a,".",b)

n = np.frompyfunc(name,2,1)
print(n(["kamal","vijay"],["k","s"]))


kamal . k
vijay . s
[None None]
